export const sideElement = "div[id=side]";
export const paneSideElement = "div[id=pane-side]";
export const conversationHeaderElement = "header[data-testid=conversation-header]";
export const composeBoxElement = "div[data-testid=compose-box]";
export const chatListHeaderElement = "header[data-testid=chatlist-header]"
export const cellFrameElement = "div[data-testid=cell-frame-container]";
export const conversationBodyElement = "div[data-testid=conversation-panel-body]";
export const menuElement = 'span[data-testid="menu"]';
export const sendElement = 'span[data-testid="send"]';
export const conversationComposeBox = '[data-testid="conversation-compose-box-input"]';
export const WA_LANGUAGE_PARAM = "WALangPref";